// dbrjs10-angular13/src/app/image-capture/image-capture.component.ts
import { Component, ViewChild, ElementRef } from '@angular/core';
import '../dynamsoft.config';
import { EnumCapturedResultItemType } from 'dynamsoft-core';
import type { BarcodeResultItem } from 'dynamsoft-barcode-reader';
import { CaptureVisionRouter } from 'dynamsoft-capture-vision-router';

@Component({
  selector: 'app-image-capture',
  templateUrl: './image-capture.component.html',
  styleUrls: ['./image-capture.component.css'],
})
export class ImageCaptureComponent {
  @ViewChild('results') resultsContainer?: ElementRef<HTMLDivElement>;

  pCvRouter?: Promise<CaptureVisionRouter>;
  isDestroyed = false;

  captureImage = async (e: Event) => {
    let files = [...((e.target! as HTMLInputElement).files as any as File[])];
    (e.target! as HTMLInputElement).value = ''; // reset input
    this.resultsContainer!.nativeElement.innerText = '';
    try {
      // ensure cvRouter is created only once
      const cvRouter = await (this.pCvRouter =
        this.pCvRouter || CaptureVisionRouter.createInstance());
      if (this.isDestroyed) return;

      for (let file of files) {
        // Decode selected image with 'ReadBarcodes_SpeedFirst' template.
        const result = await cvRouter.capture(file, 'ReadBarcodes_SpeedFirst');
        if (this.isDestroyed) return;

        // Print file name if there's multiple files
        if (files.length > 1) {
          this.resultsContainer!.nativeElement.innerText += `\n${file.name}:\n`;
        }
        for (let _item of result.items) {
          if (_item.type !== EnumCapturedResultItemType.CRIT_BARCODE) {
            continue; // check if captured result item is a barcode
          }
          let item = _item as BarcodeResultItem;
          this.resultsContainer!.nativeElement.innerText += item.text + '\n'; // output the decoded barcode text
          console.log(item.text);
        }
        // If no items are found, display that no barcode was detected
        if (!result.items.length)
          this.resultsContainer!.nativeElement.innerText +=
            'No barcode found\n';
      }
    } catch (ex: any) {
      let errMsg = ex.message || ex;
      console.error(errMsg);
      alert(errMsg);
    }
  };

  // dispose cvRouter when it's no longer needed
  async ngOnDestroy() {
    this.isDestroyed = true;
    if (this.pCvRouter) {
      try {
        (await this.pCvRouter).dispose();
      } catch (_) {}
    }
  }
}

// ticket-u22409/src/components/ImageCapture/ImageCapture.tsx
import React, { useCallback, useState } from "react";
import { EnumBarcodeFormat } from "dynamsoft-barcode-reader-bundle";
import "./ImageCapture.css";
import { useDynamsoftBarcodes } from '../../hooks/useDynamsoftBarcode'

function ImageCapture() {
  let [resultText, setResultText] = useState("");

  const { readBarcodes } = useDynamsoftBarcodes();

  const captureImage = useCallback(async (e: React.ChangeEvent<HTMLInputElement>) => {
    let files = [...(e.target.files as any as File[])];
    e.target.value = ""; // reset input
    setResultText("decoding...");

    let _resultText = "";
    for (let file of files) {
      try {
        const txts = await readBarcodes(file, 
          EnumBarcodeFormat.BF_CODE_128 | 
          EnumBarcodeFormat.BF_CODE_39 | 
          EnumBarcodeFormat.BF_CODE_39_EXTENDED | 
          EnumBarcodeFormat.BF_QR_CODE |
          EnumBarcodeFormat.BF_DATAMATRIX
        );

        // Print file name if there's multiple files
        if (files.length > 1) {
          _resultText += `\n${file.name}:\n`;
        }
        for (let txt of txts) {
          _resultText += txt + "\n"
        }
        // If no items are found, display that no barcode was detected
        if (!txts.length) {
          _resultText += "No barcode found\n";
        };
      } catch (ex: any) {
        let errMsg = ex.message || ex;
        console.error(ex);
        _resultText += errMsg + '\n';
      }

      setResultText(_resultText);
    }
  }, [readBarcodes]);

  return (
    <div className="image-capture-container">
      <div className="input-container">
        <input type="file" multiple accept=".jpg,.jpeg,.icon,.gif,.svg,.webp,.png,.bmp" onChange={captureImage} />
      </div>
      <div className="results">{resultText}</div>
    </div>
  );
}

export default ImageCapture;
